# Build the React app
FROM node:22

ARG VITE_BACKEND_ROOT
ENV VITE_BACKEND_ROOT=$VITE_BACKEND_ROOT

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the React app
ENTRYPOINT npm run dev
